//
//  BreedQuizModels.swift
//  CatApiTest
//
//  Created by Alex Kiritsa on 22.05.2020.
//  Copyright (c) 2020 Alex Kiritsa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BreedQuiz {
    enum Model {
        struct Request {
            enum RequestType {
                case getBreed
            }
        }
        struct Response {
            enum ResponseType {
                case presentBreed(breeds: [BreedResponse], image: BreedImageResponse)
            }
        }
        struct ViewModel {
            enum ViewModelData {
                case displayBreedQuiz(quizViewModel: BreedQuizViewModel)
            }
        }
    }
}

struct BreedQuizViewModel {
    let imageUrl: String
    let buttonText: [String]
    let currentBreed: BreedResponse
}
