//
//  BreedQuizWorker.swift
//  CatApiTest
//
//  Created by Alex Kiritsa on 22.05.2020.
//  Copyright (c) 2020 Alex Kiritsa. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BreedQuizWorker {
    
    var fetcher = NetworkDataFetcher()
    
    func getBreed(completion: @escaping ([BreedResponse]?) -> Void) {
        fetcher.getBreed { (breedResponse) in
            completion(breedResponse)
        }
    }
    
    func getImage(breed: BreedResponse, completion: @escaping ([BreedImageResponse]?) -> Void) {
        fetcher.getImageUrl(breed) { (imageResponse) in
            completion(imageResponse)
        }
    }
}
